import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by nextjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[100%] mx-auto">
        <div className="min-h-screen">
          <Navbar />
          {children}
        </div>
        <footer className="bg-cyan-700 py-5 text-white text-center">
          All rights reserved by Mazharul Islam || created 2025
        </footer>
      </body>
    </html>
  );
}
